package de.zabuza.webcrawler.database;

import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import de.zabuza.webcrawler.enums.SlotType;

/**
 * Utility class that links slotTypes and their ids.
 * @author Zabuza {@literal <zabuza.dev@gmail.com>}
 *
 */
public final class SlotTypeTableDb {
	/**
	 * Singleton instance of this class.
	 */
	private static SlotTypeTableDb instance = null;
	/**
	 * Separator character for values in the text representation.
	 */
	private static final String VALUE_SEPARATOR = ",";
	/**
	 * Enclosing character for values in the text representation.
	 */
	private static final String ENCLOSER = "\"";
	/**
	 * Separator character for entries in the text representation.
	 */
	public static final String ENTRY_SEPARATOR = ";";
	/**
	 * Dictionary for id to slot type access.
	 */
	private final Map<Integer, SlotType> idToSlotType = new HashMap<Integer, SlotType>();
	/**
	 * Dictionary for slot type to id access.
	 */
	private final Map<SlotType, Integer> slotTypeToId = new HashMap<SlotType, Integer>();
	/**
	 * Dictionary for slot type to description access.
	 */
	private final Map<SlotType, String> slotTypeToDescription = new HashMap<SlotType, String>();
	/**
	 * Creates a new slotTypeTableDb object.
	 */
	private SlotTypeTableDb() {
		//Generated by SlotTypeTableParseTool : slotTypeTable.csv
		idToSlotType.put(1, SlotType.CO);
		slotTypeToDescription.put(SlotType.CO, "Commanding Officer");
		idToSlotType.put(2, SlotType.XO);
		slotTypeToDescription.put(SlotType.XO, "Executive Officer");
		idToSlotType.put(3, SlotType.MIO);
		slotTypeToDescription.put(SlotType.MIO, "Military Intelligence Officer");
		idToSlotType.put(4, SlotType.COL);
		slotTypeToDescription.put(SlotType.COL, "Chief of Logistics");
		idToSlotType.put(5, SlotType.JTAC);
		slotTypeToDescription.put(SlotType.JTAC, "Joint Terminal Attack Controller");
		idToSlotType.put(6, SlotType.PL);
		slotTypeToDescription.put(SlotType.PL, "Platoon Leader");
		idToSlotType.put(7, SlotType.PSG);
		slotTypeToDescription.put(SlotType.PSG, "Platoon Sergeant");
		idToSlotType.put(8, SlotType.FO);
		slotTypeToDescription.put(SlotType.FO, "Forward Observer");
		idToSlotType.put(9, SlotType.SL);
		slotTypeToDescription.put(SlotType.SL, "Squad Leader");
		idToSlotType.put(10, SlotType.TL);
		slotTypeToDescription.put(SlotType.TL, "Team Leader");
		idToSlotType.put(11, SlotType.FTL);
		slotTypeToDescription.put(SlotType.FTL, "Fireteam Leader");
		idToSlotType.put(12, SlotType.AR);
		slotTypeToDescription.put(SlotType.AR, "Automatic Rifleman");
		idToSlotType.put(13, SlotType.GRE);
		slotTypeToDescription.put(SlotType.GRE, "Grenadier");
		idToSlotType.put(14, SlotType.RFL);
		slotTypeToDescription.put(SlotType.RFL, "Rifleman");
		idToSlotType.put(15, SlotType.CMDC);
		slotTypeToDescription.put(SlotType.CMDC, "Combat Medic");
		idToSlotType.put(16, SlotType.DM);
		slotTypeToDescription.put(SlotType.DM, "Designated Marksman");
		idToSlotType.put(17, SlotType.ATR);
		slotTypeToDescription.put(SlotType.ATR, "Anti-Tank Rifleman");
		idToSlotType.put(18, SlotType.AAR);
		slotTypeToDescription.put(SlotType.AAR, "Anti-Air Rifleman");
		idToSlotType.put(19, SlotType.MG);
		slotTypeToDescription.put(SlotType.MG, "Machine Gunner");
		idToSlotType.put(20, SlotType.AMG);
		slotTypeToDescription.put(SlotType.AMG, "Assistant Machine Gunner");
		idToSlotType.put(21, SlotType.AT);
		slotTypeToDescription.put(SlotType.AT, "Anti-Tank Specialist");
		idToSlotType.put(22, SlotType.AAT);
		slotTypeToDescription.put(SlotType.AAT, "Assistant Anti-Tank Specialist");
		idToSlotType.put(23, SlotType.AA);
		slotTypeToDescription.put(SlotType.AA, "Anti-Air Specialist");
		idToSlotType.put(24, SlotType.AAA);
		slotTypeToDescription.put(SlotType.AAA, "Assistant Anti-Air Specialist");
		idToSlotType.put(25, SlotType.SNP);
		slotTypeToDescription.put(SlotType.SNP, "Sniper");
		idToSlotType.put(26, SlotType.SPT);
		slotTypeToDescription.put(SlotType.SPT, "Spotter");
		idToSlotType.put(27, SlotType.TPL);
		slotTypeToDescription.put(SlotType.TPL, "Tank Platoon Leader");
		idToSlotType.put(28, SlotType.TPS);
		slotTypeToDescription.put(SlotType.TPS, "Tank Platoon Sergeant");
		idToSlotType.put(29, SlotType.TC);
		slotTypeToDescription.put(SlotType.TC, "Tank Commander");
		idToSlotType.put(30, SlotType.GNR);
		slotTypeToDescription.put(SlotType.GNR, "Gunner");
		idToSlotType.put(31, SlotType.DRV);
		slotTypeToDescription.put(SlotType.DRV, "Driver");
		idToSlotType.put(32, SlotType.LOG);
		slotTypeToDescription.put(SlotType.LOG, "Logistician");
		idToSlotType.put(33, SlotType.MDC);
		slotTypeToDescription.put(SlotType.MDC, "Medic");
		idToSlotType.put(34, SlotType.PIL);
		slotTypeToDescription.put(SlotType.PIL, "Pilot");
		idToSlotType.put(35, SlotType.CPIL);
		slotTypeToDescription.put(SlotType.CPIL, "Co-Pilot");
		idToSlotType.put(36, SlotType.WSO);
		slotTypeToDescription.put(SlotType.WSO, "Weapon Systems Officer");
		idToSlotType.put(37, SlotType.WCO);
		slotTypeToDescription.put(SlotType.WCO, "Wing Commander");
		idToSlotType.put(38, SlotType.ACSO);
		slotTypeToDescription.put(SlotType.ACSO, "Artillery Command Systems Operator");
		idToSlotType.put(39, SlotType.SPEC);
		slotTypeToDescription.put(SlotType.SPEC, "Special Forces");
		idToSlotType.put(40, SlotType.ZC_PLUS);
		slotTypeToDescription.put(SlotType.ZC_PLUS, "Zeus/CO+/etc.");
		idToSlotType.put(41, SlotType.CE);
		slotTypeToDescription.put(SlotType.CE, "Combat Engineer");
		idToSlotType.put(42, SlotType.OTHER);
		slotTypeToDescription.put(SlotType.OTHER, "Other");
		idToSlotType.put(43, SlotType.RESERVE);
		slotTypeToDescription.put(SlotType.RESERVE, "Reserve");
		
		for (Entry<Integer, SlotType> entry : idToSlotType.entrySet()) {
			slotTypeToId.put(entry.getValue(), entry.getKey());
		}
	}
	
	/**
	 * Returns the slot type that is represented by the given id.
	 * @param id Id of the slot type
	 * @return Slot type that is represented by the given id
	 */
	public SlotType getSlotType(int id) {
		SlotType type = idToSlotType.get(id);
		if (type == null) {
			System.err.println("Database table does not know slot type with id: " + id);
		}
		return type;
	}
	/**
	 * Returns the id of the given slot type.
	 * @param type Slot type to get id of
	 * @return Id of the slot type
	 */
	public Integer getId(SlotType type) {
		Integer id = slotTypeToId.get(type);
		if (id == null) {
			System.err.println("Database table does not know id of slot type: " + type);
		}
		return id;
	}
	
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		for (Entry<Integer, SlotType> entry : idToSlotType.entrySet()) {
			int id = entry.getKey();
			String description = slotTypeToDescription.get(entry.getValue());
			String slotTypeText = entry.getValue() + "";
			if (slotTypeText.equals("COL")) {
				slotTypeText = "CoL";
			} else if (slotTypeText.equals("ZC_PLUS")) {
				slotTypeText = "ZC+";
			} else if (slotTypeText.equals("OTHER")) {
				slotTypeText = "N/A";
			} else if (slotTypeText.equals("RESERVE")) {
				slotTypeText = "RE";
			}
			builder.append(ENCLOSER + id + ENCLOSER + VALUE_SEPARATOR);
			builder.append(ENCLOSER + slotTypeText + ENCLOSER + VALUE_SEPARATOR);
			builder.append(ENCLOSER + description + ENCLOSER + ENTRY_SEPARATOR);
		}
		builder.delete(builder.length() - ENTRY_SEPARATOR.length(), builder.length());
		return builder.toString();
	}
	
	/**
	 * Gets the singleton instance of this class.
	 * @return Singleton instance of this class
	 */
	public static SlotTypeTableDb getInstance() {
		if (instance == null) {
			instance = new SlotTypeTableDb();
		}
		return instance;
	}
}
